"use client";

import { useEffect, useState } from "react";
import { SourceBadge, EvidenceBadge } from "./SourceBadge";
import { Glossarized } from "./GlossaryTooltip";

export type PaperLike = {
  id: string;
  title: string;
  bluf: string;
  clinicalImplications?: string | null;
  abstract?: string | null;
  authors: string[];
  journal?: string | null;
  year?: number | null;
  source: string;          // e.g., "PubMed"
  sourceTone?: "pink" | "lavender" | "babyblue" | "neutral";
  evidenceKind?: string | null; // rct, meta-analysis, etc.
  url: string;
  topics?: string[];
  keyStats?: { label: string; value: string }[];
  isAiSummarized?: boolean; // if BLUF was generated by AI
  readingMinutes?: number | null;
  jargon?: "plain" | "medium" | "heavy" | null;
};

const jargonLabel: Record<string, string> = {
  plain: "Plain English",
  medium: "Some jargon",
  heavy: "Heavy jargon",
};

const isSampleId = (id: string) => id.startsWith("sample-");

export function PaperCard({ paper }: { paper: PaperLike }) {
  const [expanded, setExpanded] = useState(false);
  const [saved, setSaved] = useState(false);
  const [savingErr, setSavingErr] = useState<string | null>(null);
  const [speaking, setSpeaking] = useState(false);
  const [notesOpen, setNotesOpen] = useState(false);
  const [note, setNote] = useState("");
  const [noteSaving, setNoteSaving] = useState(false);
  const [noteSavedAt, setNoteSavedAt] = useState<number | null>(null);

  useEffect(() => {
    return () => {
      if (typeof window !== "undefined") window.speechSynthesis?.cancel();
    };
  }, []);

  // Load existing note (skip for sample papers)
  useEffect(() => {
    if (!notesOpen || isSampleId(paper.id)) return;
    let cancelled = false;
    fetch(`/api/notes?paperId=${encodeURIComponent(paper.id)}`)
      .then((r) => r.json())
      .then((data) => {
        if (!cancelled && data.note) setNote(data.note);
      })
      .catch(() => {});
    return () => {
      cancelled = true;
    };
  }, [notesOpen, paper.id]);

  async function toggleSave() {
    setSavingErr(null);
    if (isSampleId(paper.id)) {
      // Sample papers don't exist in DB — just toggle locally
      setSaved((v) => !v);
      return;
    }
    const next = !saved;
    setSaved(next);
    try {
      const res = await fetch("/api/bookmarks", {
        method: next ? "POST" : "DELETE",
        headers: { "content-type": "application/json" },
        body: JSON.stringify({ paperId: paper.id }),
      });
      if (!res.ok) {
        const data = await res.json().catch(() => ({}));
        if (data.error) setSavingErr(data.error);
        setSaved(!next);
      }
    } catch {
      setSaved(!next);
      setSavingErr("Network error");
    }
  }

  async function saveNote() {
    if (isSampleId(paper.id)) {
      setSavingErr("Notes save once papers are pulled from a real source.");
      return;
    }
    setNoteSaving(true);
    setSavingErr(null);
    try {
      const res = await fetch("/api/notes", {
        method: "PUT",
        headers: { "content-type": "application/json" },
        body: JSON.stringify({ paperId: paper.id, body: note }),
      });
      if (res.ok) setNoteSavedAt(Date.now());
    } catch {
      setSavingErr("Couldn't save note");
    } finally {
      setNoteSaving(false);
    }
  }

  function toggleAudio() {
    if (typeof window === "undefined") return;
    const synth = window.speechSynthesis;
    if (!synth) {
      alert("Audio not supported in this browser.");
      return;
    }
    if (speaking) {
      synth.cancel();
      setSpeaking(false);
      return;
    }
    const text = [
      paper.bluf,
      paper.clinicalImplications ? `Clinical implications: ${paper.clinicalImplications}` : "",
      paper.abstract ?? "",
    ]
      .filter(Boolean)
      .join(". ");
    const utt = new SpeechSynthesisUtterance(text);
    utt.rate = 1.05;
    utt.pitch = 1.0;
    utt.onend = () => setSpeaking(false);
    utt.onerror = () => setSpeaking(false);
    setSpeaking(true);
    synth.speak(utt);
  }

  return (
    <article className="rounded-3xl bg-white/85 backdrop-blur-sm border border-pink-100 shadow-soft p-5 sm:p-6 transition-shadow hover:shadow-pop">
      {/* badges */}
      <div className="flex flex-wrap gap-2 mb-3">
        <SourceBadge source={paper.source} tone={paper.sourceTone ?? "pink"} />
        {paper.evidenceKind && <EvidenceBadge kind={paper.evidenceKind} />}
        {paper.year && (
          <span className="chip bg-cream text-ink-mute border border-pink-100">
            {paper.year}
          </span>
        )}
        {paper.readingMinutes != null && (
          <span className="chip bg-babyblue-50 text-babyblue-600 border border-babyblue-200">
            ⏱ {paper.readingMinutes} min
          </span>
        )}
        {paper.jargon && (
          <span className="chip bg-lavender-50 text-lavender-600 border border-lavender-200">
            {paper.jargon === "plain" ? "🌷" : paper.jargon === "medium" ? "🌸" : "🌹"} {jargonLabel[paper.jargon]}
          </span>
        )}
      </div>

      {/* BLUF */}
      <p className="font-display font-bold text-lg sm:text-xl leading-snug text-ink mb-2">
        <Glossarized text={paper.bluf} />
      </p>
      {paper.isAiSummarized && (
        <p className="text-[11px] uppercase tracking-wide font-bold text-lavender-500 mb-2 flex items-center gap-1">
          <span>🤖</span> AI summary — original abstract below
        </p>
      )}

      {/* Title (smaller) */}
      <p className="text-sm font-semibold text-ink-soft mb-3">{paper.title}</p>

      {/* Clinical implications block */}
      {paper.clinicalImplications && (
        <div className="rounded-2xl bg-gradient-to-br from-pink-50 to-lavender-50 border border-pink-200 px-4 py-3 mb-4">
          <p className="text-[10px] uppercase tracking-wider font-bold text-pink-700 mb-1 flex items-center gap-1">
            <span>💡</span> Implications for clinical practice
            {paper.isAiSummarized && (
              <span className="text-lavender-500 ml-1">· AI-assisted</span>
            )}
          </p>
          <p className="text-sm text-ink leading-relaxed">
            <Glossarized text={paper.clinicalImplications} />
          </p>
        </div>
      )}

      {/* Key stats row */}
      {paper.keyStats && paper.keyStats.length > 0 && (
        <div className="grid grid-cols-3 gap-2 mb-4">
          {paper.keyStats.slice(0, 3).map((s, i) => (
            <div
              key={i}
              className="rounded-xl bg-gradient-to-br from-pink-50 via-lavender-50 to-babyblue-50 border border-pink-100 px-3 py-2"
            >
              <div className="text-[10px] uppercase tracking-wider text-ink-mute font-bold">
                {s.label}
              </div>
              <div className="font-display font-bold text-ink text-sm mt-0.5">
                {s.value}
              </div>
            </div>
          ))}
        </div>
      )}

      {/* Authors / journal */}
      <p className="text-xs text-ink-mute mb-4">
        {paper.authors.slice(0, 3).join(", ")}
        {paper.authors.length > 3 ? " et al." : ""}
        {paper.journal ? ` · ${paper.journal}` : ""}
      </p>

      {/* topics */}
      {paper.topics && paper.topics.length > 0 && (
        <div className="flex flex-wrap gap-1.5 mb-4">
          {paper.topics.map((t) => (
            <span
              key={t}
              className="chip bg-pink-50 text-pink-600 border border-pink-100"
            >
              {t}
            </span>
          ))}
        </div>
      )}

      {/* Expand toggle */}
      {paper.abstract && (
        <button
          onClick={() => setExpanded((v) => !v)}
          className="text-sm font-display font-semibold text-lavender-600 hover:text-lavender-700"
        >
          {expanded ? "Hide abstract ↑" : "Show abstract ↓"}
        </button>
      )}
      {expanded && paper.abstract && (
        <p className="mt-3 text-sm text-ink-soft leading-relaxed whitespace-pre-line">
          <Glossarized text={paper.abstract} />
        </p>
      )}

      {/* Actions */}
      <div className="mt-5 flex flex-wrap items-center gap-2">
        <a
          href={paper.url}
          target="_blank"
          rel="noopener noreferrer"
          className="inline-flex items-center gap-1.5 rounded-full bg-gradient-to-r from-pink-400 to-lavender-400 hover:from-pink-500 hover:to-lavender-500 text-white font-display font-semibold text-sm px-4 py-2 shadow-soft transition-all"
        >
          Read source <span aria-hidden="true">↗</span>
        </a>
        <button
          onClick={toggleSave}
          className={`inline-flex items-center gap-1.5 rounded-full border-2 font-display font-semibold text-sm px-4 py-2 transition-all ${
            saved
              ? "bg-pink-100 border-pink-300 text-pink-700"
              : "border-pink-200 hover:border-pink-300 text-pink-600"
          }`}
          aria-label={saved ? "Unsave paper" : "Save paper"}
        >
          {saved ? "🔖 Saved" : "🔖 Save"}
        </button>
        <button
          onClick={toggleAudio}
          className={`inline-flex items-center gap-1.5 rounded-full border-2 font-display font-semibold text-sm px-4 py-2 transition-all ${
            speaking
              ? "bg-lavender-100 border-lavender-300 text-lavender-700"
              : "border-lavender-200 hover:border-lavender-300 text-lavender-600"
          }`}
          aria-label={speaking ? "Stop audio" : "Listen"}
        >
          {speaking ? "⏹ Stop" : "🎧 Listen"}
        </button>
        <button
          onClick={() => setNotesOpen((v) => !v)}
          className={`inline-flex items-center gap-1.5 rounded-full border-2 font-display font-semibold text-sm px-4 py-2 transition-all ${
            notesOpen
              ? "bg-babyblue-100 border-babyblue-300 text-babyblue-700"
              : "border-babyblue-200 hover:border-babyblue-300 text-babyblue-600"
          }`}
          aria-label={notesOpen ? "Hide notes" : "Add note"}
        >
          📝 {notesOpen ? "Hide note" : "Note"}
        </button>
      </div>

      {/* Notes */}
      {notesOpen && (
        <div className="mt-4 rounded-2xl bg-cream border border-babyblue-100 p-3">
          <textarea
            value={note}
            onChange={(e) => setNote(e.target.value)}
            placeholder="Your private notes — observations, applications for clients, follow-up reading…"
            rows={3}
            className="w-full rounded-xl bg-white/80 border border-babyblue-100 focus:border-babyblue-300 outline-none px-3 py-2 text-sm leading-relaxed resize-y"
          />
          <div className="flex items-center justify-between mt-2">
            <span className="text-[10px] text-ink-mute">
              {isSampleId(paper.id)
                ? "Notes save once papers are pulled from a real source."
                : noteSavedAt
                ? `✓ saved ${new Date(noteSavedAt).toLocaleTimeString()}`
                : "Private to your account."}
            </span>
            <button
              onClick={saveNote}
              disabled={noteSaving || isSampleId(paper.id)}
              className="rounded-full bg-gradient-to-r from-babyblue-400 to-lavender-400 hover:from-babyblue-500 hover:to-lavender-500 text-white font-display font-bold text-xs px-3 py-1.5 disabled:opacity-50 transition-all"
            >
              {noteSaving ? "Saving…" : "Save note"}
            </button>
          </div>
        </div>
      )}

      {savingErr && (
        <p className="mt-2 text-xs text-pink-600 font-semibold">{savingErr}</p>
      )}
    </article>
  );
}
